FROM python:3.8.5

RUN apt-get install bash && \
    pip install mypy==0.770 mypy2junit

ADD .jenkins/run_mypy.sh /bin

ADD setup.py /build/setup.py
ADD ampel /build/ampel
RUN cd /build && pip install -e .

