pipeline {
  agent any
  stages {
    stage('mypy') {
      steps {
        script {
          docker.image("cytopia/mypy").inside(
            " -v ${workspace}:/workspace"
          ) {
              sh '#!/bin/sh\n rm /workspace/*.xml || true'
              sh '#!/bin/sh\n pip install -r /workspace/requirements.txt'
              sh '#!/bin/sh\n cd /workspace; mypy ampel --junit-xml mypy.xml'
          }
        }
      }
      post {
        always {
          junit 'mypy.xml'
        }
      }
    }
  }
}