pipeline {
  agent none
  stages {
    stage('dependencies') {
      agent any
      steps {
          dir(path: '.jenkins/Ampel-core') {
            git(url: 'https://github.com/AmpelProject/Ampel-core', credentialsId: 'github')
          }
      }
    }
    stage('build') {
      agent {
        dockerfile {
          filename '.jenkins/Dockerfile.build'
        }
      }
      steps {
        sh 'mypy ampel --junit-xml mypy.xml'
      }
      post {
        always {
          junit 'mypy.xml'
        }
      }
    }
  }
}