name: Static analysis

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel mypy==0.800
    - run: python -m pip install -e .
    - run: mypy --namespace-packages -p ampel
